### ISSUE TITLE
No badges detected for repo with 4 badges

### ISSUE THREAD

**Issue by paulyoung** [defunctzombie/badginator#1]
[This repo](https://github.com/BlessCSS/bless) has 4 badges but 0 are reported:

![](https://badginator.herokuapp.com/BlessCSS/bless.svg)

**Comment by defunctzombie** [comment]
Repo badges are detected using a naive regexp approach:

https://github.com/defunctzombie/badginator/blob/master/index.js#L49

Looking at the readme in that repo, it adds badges using a style I have not seen before with markdown references I guess?

Is this common? If it is, then it would be a simple matter of adding that style to the regexp check.

**Comment by paulyoung** [comment]
I'm not sure how common it is, just wanted to give you a heads up.

**Comment by necenzurat** [comment]
1. it's more practical to count all the `.svg` in a readme.md file
2. another issueis that styleci uses something like this `https://styleci.io/repos/7548986/shield?style=flat`

**Comment by defunctzombie** [comment]
@necenzurat that would omit the PNG badges (not sure how prevalent those are but some folks might still be using them).

**Comment by defunctzombie** [comment]
I've been working on improving badge detection. I am now testing a new approach which uses image analysis on the images found in a readme.

Before:

![](http://badginator.herokuapp.com/BlessCSS/bless.svg)

After:

![](http://badginator.herokuapp.com/BlessCSS/bless.svg?image_analysis=1)

Once I give it some more testing, I will make it the default. This will also solve having to do #7

**Comment by defunctzombie** [comment]
closing since image analysis is now on by default

**Comment by paulyoung** [comment]
Just curious, why does the badge at the top of this issue and the info in the README still result in the count being 0?

**Comment by defunctzombie** [comment]
Github caches all images so it might take some time before it decides it wants to re-fetch the badge image.
