### ISSUE TITLE
Badginator doesn't count itself

### ISSUE THREAD

**Issue by michaelzoidl** [defunctzombie/badginator#2]
When i embed for example the badginator in a repo with 4 badges - the badginator counts "4 badges"... but .. the badginator is also a badge, right? 

So the right number should be 5.

![](http://1.media.dorkly.cvcdn.com/50/27/0d41808f60af8871fa122b3b0f37ab1b.gif)

**Comment by defunctzombie** [comment]
@michaelzoidl example? Badginator should be counting itself. It may be that the image has not updated due to how github readme images are cached.
