### ISSUE TITLE
Error 523

### ISSUE THREAD

**Issue by breakzplatform** [defunctzombie/badginator#6]
![screen shot 2016-01-31 at 4 10 40 am](https://cloud.githubusercontent.com/assets/597126/12700810/a4eb2c1e-c7d0-11e5-9e0c-d6fe7afd84cd.png)

**Comment by defunctzombie** [comment]
? I don't understand what this is showing. Can you clarify what you tried to open to get this?

**Comment by breakzplatform** [comment]
I'm getting it some (in fact a lot) times when I access badge url

**Comment by defunctzombie** [comment]
Hm, gotcha. Maybe the shields.io is having issues? Maybe I should switch to generating my own badge images instead of using shields.io to do the image gen.

**Comment by breakzplatform** [comment]
Maybe they're blocking a high request number from a unique source (like your website). What about redirect `https://badginator.herokuapp.com/<username>/<repo>.svg` to `https://img.shields.io/badge/<SUBJECT>-<STATUS>-<COLOR>.svg` after get the values?

**Comment by defunctzombie** [comment]
Yea, I think that could be a good temp solution instead of proxy until we render our own badges. Only concern is that github image resolution would follow the redirect.

**Comment by breakzplatform** [comment]
Good. I think I can close this issue right now.

Thats a excellent (and funny) project, tell me if you need help if testing or something.
